#### 5.1.
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5E)-1 где Е – единичная матрица размера 5х5.


In [2]:
import numpy as np

In [3]:
m = np.array([1, 2, 3], float)
n = np.array([4, 5, 6], float)
print(f'm = {m}')
print(f'n = {n}')

m = [1. 2. 3.]
n = [4. 5. 6.]


In [4]:
# векторное произведение
print(np.cross(m, n))

[-3.  6. -3.]


In [5]:
# скалярное произведение
print(np.dot(m, n))
print(np.inner(m, n))

32.0
32.0


In [6]:
# смешанное произведение
print(np.dot(m, np.cross(m, n)))

0.0


In [7]:
E = np.dot(1, np.identity(5))
E

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
A = np.dot(5, E)
A

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [9]:
A_inv = np.linalg.inv(A)
A_inv

array([[0.2, 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0.2]])

In [10]:
# проверка:
print(np.round(np.dot(A, A_inv), 0))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 5.2.
Вычислите определитель:


In [11]:
M = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)
M

array([[1., 2., 3.],
       [4., 0., 6.],
       [7., 8., 9.]])

In [12]:
det_M = np.linalg.det(M)
print(np.round(det_M, 0))

60.0


#### 5.3.
1. Вычислите матрицу, обратную данной:


In [13]:
G = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)
G

array([[1., 2., 3.],
       [4., 0., 6.],
       [7., 8., 9.]])

In [14]:
G_inv = np.linalg.inv(G)
G_inv

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [15]:
# проверка:
print(np.round(np.dot(G, G_inv), 0))

[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]


Приведите пример матрицы 4х4, ранг которой равен 1.


In [18]:
v =np.array([1, 2, 3, 4])
F = np.array([v * 1, v * 2, v * 3, v * 4], float)
F

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  4.,  6.,  8.],
       [ 3.,  6.,  9., 12.],
       [ 4.,  8., 12., 16.]])

#### 5.4.
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)


In [20]:
a = np.array([1, 5], float)
b = np.array([2, 8], float)
print(f'a = {a}')
print(f'b = {b}')

a = [1. 5.]
b = [2. 8.]


In [21]:
ab = np.dot(a, b)
ab

42.0

##### 5.5

(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) Вычислите смешанное произведение трех векторов:


In [22]:
x = np.array([1, 5, 0], float)
y = np.array([2, 8, 7], float)
z = np.array([7, 1.5, 3], float)
print(f'x = {x}')
print(f'y = {y}')
print(f'z = {z}')

x = [1. 5. 0.]
y = [2. 8. 7.]
z = [7.  1.5 3. ]


In [23]:
xyz = np.dot(x, np.cross(y, z))
xyz

228.5